controllers:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/controllers/**/*'

models:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/models/**/*'

views:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/views/**/*'

jobs:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/jobs/**/*'

mailers:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/mailers/**/*'

channels:
  - changed-files:
      - any-glob-to-any-file:
          - 'app/channels/**/*'

lib:
  - changed-files:
      - any-glob-to-any-file:
          - 'lib/**/*'

config:
  - changed-files:
      - any-glob-to-any-file:
          - 'config/**/*'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - 'README.md'
          - 'AGENTS.md'

meeting-notes:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/meeting notes/**/*'

database:
  - changed-files:
      - any-glob-to-any-file:
          - 'db/seeds.rb'
          - 'db/schema.rb'
          - 'db/structure.sql'

migrations:
  - changed-files:
      - any-glob-to-any-file:
          - 'db/migrate/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'spec/**/*'
          - 'features/**/*'

tests-rspec:
  - changed-files:
      - any-glob-to-any-file:
          - 'spec/**/*'
          - '.rspec'

tests-cucumber:
  - changed-files:
      - any-glob-to-any-file:
          - 'features/**/*'
          - 'cucumber.yml'

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'
          - 'bin/**/*'
          - 'Dockerfile'
